// AccountDeletionPage.js

import React from 'react';

const AccountDeletionPage = () => {
  return (
    <div className="min-h-screen flex items-center justify-center bg-gray-100">
      <div className="max-w-md w-full bg-white p-8 rounded shadow-lg text-black">
        <h2 className="text-2xl font-semibold mb-4">Account Deletion Request</h2>

        <p>
          If you wish to delete your account on Rondevu, please follow the steps below:
        </p>

        {/* Steps for Account Deletion */}
        <ol className="list-decimal pl-6 mb-6">
          <li>Email us at <strong>support@rondevu.app</strong> from the email associated with your Rondevu account.</li>
          <li>In your email, clearly state that you want to request account deletion.</li>
          <li>Our support team will verify your request and process the account deletion.</li>
          <li>Once the deletion is complete, you will receive a confirmation email.</li>
        </ol>

        {/* Data Removal Information */}
        <p>
          Please note that when your account is deleted:
        </p>
        <ul className="list-disc pl-6 mb-6">
          <li>Your profile information will be removed from the app.</li>
          <li>Content generated by you (e.g., posts, comments) will not be deleted to preserve the integrity of the community, but your association with that content will be anonymized.</li>
        </ul>

        {/* Additional Information */}
        <p>
          If you want to delete specific information in your account (e.g., certain posts or details), but not your entire account, please contact us at <strong>support@rondevu.app</strong>. Our support team will assist you in the selective removal of information.
        </p>

        {/* Contact Us */}
        <p>
          If you have any questions or concerns regarding the account deletion process, please reach out to us at <strong>support@rondevu.app</strong>.
        </p>
      </div>
    </div>
  );
};

export default AccountDeletionPage;
